ENS160.SetTemp(witelo.temperature_aht20())
ENS160.SetHumidity(witelo.humidity_aht20())
basic.forever(function () {
    witelo.clear()
    witelo.drawText("- Witelo Raumklima -", 5, 0, witelo.UpdateMode.Off)
    witelo.drawText("Luftfeuchte", 0, 15, witelo.UpdateMode.Off)
    witelo.drawText(convertToText(witelo.humidity_aht20()), 95, 15, witelo.UpdateMode.Off)
    witelo.drawText("Temperatur", 0, 25, witelo.UpdateMode.Off)
    witelo.drawText(convertToText(witelo.temperature_aht20()), 95, 25, witelo.UpdateMode.Off)
    witelo.drawText("Luftqualität", 0, 35, witelo.UpdateMode.Off)
    witelo.drawText(convertToText(witelo.api_ens160()), 95, 35, witelo.UpdateMode.Off)
    witelo.drawText("CO2 Äquivalent", 0, 45, witelo.UpdateMode.Off)
    witelo.drawText(convertToText(witelo.eco2_ens160()), 95, 45, witelo.UpdateMode.Off)
    witelo.drawText("TVOCs", 0, 55, witelo.UpdateMode.Off)
    witelo.drawText(convertToText(witelo.tvoc_ens160()), 95, 55, witelo.UpdateMode.Off)
    witelo.update()
})
