basic.forever(function () {
    witelo.clear()
    witelo.drawText("Birgits witelo Projekt", 0, 0)
    witelo.drawText("Luftfeuchte", 0, 10)
    witelo.drawText(convertToText(witelo.humidity_aht20()), 100, 10)
    witelo.drawText("Temperatur", 0, 20)
    witelo.drawText(convertToText(witelo.temperature_aht20()), 100, 20)
    witelo.drawText("Temperatur", 0, 30)
    witelo.drawText(convertToText(witelo.temperature_bmp280()), 100, 30)
    witelo.update()
})
