basic.forever(function () {
    witelo.drawText("Hallo", 0, 0)
    witelo.drawText("Luftqualität", 0, 10)
    witelo.drawText(convertToText(ens160.aqi()), 80, 10)
    witelo.drawText("eCO2", 0, 20)
    witelo.drawText(convertToText(ens160.eco2()), 80, 20)
    witelo.drawText("TVOC", 0, 30)
    witelo.drawText(convertToText(ens160.tvoc()), 80, 30)
    witelo.drawText("Luftfeuchte", 0, 40)
    witelo.drawText(convertToText(aht2x.humidity()), 80, 40)
    witelo.drawText("Temperatur", 0, 50)
    witelo.drawText(convertToText(Math.round(aht2x.temperature())), 100, 50)
    witelo.drawText("°C", 110, 50)
    witelo.update()
    witelo.clear()
})
